In [9]:
#(1)Recursive Depth First Search Algorithm

import csv

# Function to read graph from CSV
def read_graph_from_csv(file_path):
    graph = {}
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            if not row or ',' not in row[0]:
                continue
            u, v = map(lambda x: x.strip().upper(), row[0].split(','))
            graph.setdefault(u, []).append(v)
            graph.setdefault(v, []).append(u)
    return graph

# Recursive DFS
def recursive_dfs(graph, node, visited=None):
    if visited is None:
        visited = set()
    visited.add(node)
    print(node, end=' ')
    for neighbor in graph.get(node, []):
        if neighbor not in visited:
            recursive_dfs(graph, neighbor, visited)

# File path
file_path = r"C:\Users\Vraj Shah\OneDrive\Desktop\graph.csv"

# Build the graph
graph = read_graph_from_csv(file_path)

# Input starting node and validate
start_node = input("Enter the starting node for DFS: ").strip().upper()

if start_node not in graph:
    print(f"Error: Node '{start_node}' not found in the graph.")
else:
    print("DFS traversal order:")
    recursive_dfs(graph, start_node)


Enter the starting node for DFS:  D


DFS traversal order:
D B A C E 

In [11]:
# 2) Non-Recursive DFS for an Undirected Graph

def read_graph():
    graph = {}
    n = int(input("Enter number of edges: "))
    print("Enter each edge as a pair of nodes (e.g., A B):")
    for _ in range(n):
        u, v = input().split()
        if u not in graph:
            graph[u] = []
        if v not in graph:
            graph[v] = []
        graph[u].append(v)
        graph[v].append(u)  # because the graph is undirected
    return graph

def non_recursive_dfs(graph, start):
    visited = set()
    stack = [start]

    print("DFS traversal order:")
    while stack:
        node = stack.pop()
        if node not in visited:
            print(node, end=' ')
            visited.add(node)
            # Add neighbors in reverse sorted order to visit them in lexical order
            for neighbor in sorted(graph[node], reverse=True):
                if neighbor not in visited:
                    stack.append(neighbor)

# Example usage
graph = read_graph()
start_node = input("Enter the starting node for DFS: ")
non_recursive_dfs(graph, start_node)


Enter number of edges:  4


Enter each edge as a pair of nodes (e.g., A B):


 A B
 B C
 C D
 B D
Enter the starting node for DFS:  A


DFS traversal order:
A B C D 

In [14]:
# 3) Breadth First Search Algorithm

from collections import deque

# Function to read the graph from user
def read_graph_from_user():
    graph = {}
    num_edges = int(input("Enter the number of edges: "))
    print("Enter each edge in the format 'node1 node2' (space separated):")
    for _ in range(num_edges):
        u, v = input().strip().split()
        u = u.strip().upper()
        v = v.strip().upper()
        if u not in graph:
            graph[u] = []
        if v not in graph:
            graph[v] = []
        graph[u].append(v)
        graph[v].append(u)  # Undirected graph
    return graph

# BFS Function
def bfs(graph, start_node):
    visited = set()
    queue = deque()

    visited.add(start_node)
    queue.append(start_node)

    while queue:
        node = queue.popleft()
        print(node, end=' ')

        for neighbor in graph.get(node, []):
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)

# Main part
graph = read_graph_from_user()
print("\nGraph structure:", graph)

start_node = input("\nEnter the starting node for BFS: ").strip().upper()

if start_node not in graph:
    print(f"Error: Node '{start_node}' not found in the graph.")
else:
    print("\nBFS traversal order:")
    bfs(graph, start_node)

Enter the number of edges:  4


Enter each edge in the format 'node1 node2' (space separated):


 A B
 B C
 A D
 C D



Graph structure: {'A': ['B', 'D'], 'B': ['A', 'C'], 'C': ['B', 'D'], 'D': ['A', 'C']}



Enter the starting node for BFS:  B



BFS traversal order:
B A C D 

In [18]:
# 4) Best FS  Algo - Directed|UnWeighted

import heapq

def read_graph_from_user():
    graph = {}
    for _ in range(int(input("Enter the number of edges: "))):
        u, v = input("Enter edge (start end): ").strip().upper().split()
        graph.setdefault(u, []).append(v)
    return graph

def read_heuristics():
    heuristics = {}
    for _ in range(int(input("Enter the number of nodes for heuristics: "))):
        node, h = input("Enter node and heuristic (node h): ").strip().upper().split()
        heuristics[node] = int(h)
    return heuristics

def best_first_search(graph, heuristics, start, goal):
    visited = set()
    queue = [(heuristics[start], start)]

    while queue:
        _, node = heapq.heappop(queue)
        if node in visited:
            continue
        print(node, end=' ')
        visited.add(node)
        if node == goal:
            print("\nGoal node reached!")
            return
        for neighbor in graph.get(node, []):
            if neighbor not in visited:
                heapq.heappush(queue, (heuristics[neighbor], neighbor))
    
    print("\nGoal node not reachable.")

# Main
graph = read_graph_from_user()
heuristics = read_heuristics()

print("\nGraph structure:", graph)
print("Heuristic values:", heuristics)

start = input("\nEnter the starting node: ").strip().upper()
goal = input("Enter the goal node: ").strip().upper()

if start not in graph:
    print(f"Error: Start node '{start}' not found in graph.")
elif goal not in heuristics:
    print(f"Error: Goal node '{goal}' not found in heuristic values.")
else:
    print("\nBest First Search traversal order:")
    best_first_search(graph, heuristics, start, goal)


Enter the number of edges:  5
Enter edge (start end):  A B
Enter edge (start end):  A C
Enter edge (start end):  B D
Enter edge (start end):  C E
Enter edge (start end):  D E
Enter the number of nodes for heuristics:  5
Enter node and heuristic (node h):  A 4
Enter node and heuristic (node h):  B 2
Enter node and heuristic (node h):  C 3
Enter node and heuristic (node h):  D 1
Enter node and heuristic (node h):  E 0



Graph structure: {'A': ['B', 'C'], 'B': ['D'], 'C': ['E'], 'D': ['E']}
Heuristic values: {'A': 4, 'B': 2, 'C': 3, 'D': 1, 'E': 0}



Enter the starting node:  A
Enter the goal node:  E



Best First Search traversal order:
A B D E 
Goal node reached!


In [19]:
# 5) Best FS  Algo - Directed|Weighted

import heapq

# Read graph
def read_graph():
    graph = {}
    for _ in range(int(input("Enter number of edges: "))):
        u, v, w = input("Edge (u v weight): ").upper().split()
        graph.setdefault(u, []).append((v, int(w)))
    return graph

# Read heuristics
def read_heuristics():
    return {node.upper(): int(h) for node, h in 
            (input("Node and Heuristic (node h): ").split() for _ in range(int(input("Enter number of nodes: "))))}

# Best First Search
def best_first_search(graph, heuristics, start, goal):
    visited, queue = set(), [(heuristics[start], start)]
    while queue:
        _, node = heapq.heappop(queue)
        if node in visited: continue
        print(node, end=' ')
        visited.add(node)
        if node == goal:
            print("\nGoal reached!")
            return
        for neighbor, _ in graph.get(node, []):
            if neighbor not in visited:
                heapq.heappush(queue, (heuristics[neighbor], neighbor))
    print("\nGoal not reachable.")

# Main
graph = read_graph()
heuristics = read_heuristics()
start, goal = input("Start node: ").strip().upper(), input("Goal node: ").strip().upper()

print("\nBest First Search Traversal:")
best_first_search(graph, heuristics, start, goal)


Enter number of edges:  5
Edge (u v weight):  A B 4
Edge (u v weight):  A C 2
Edge (u v weight):  B D 5
Edge (u v weight):  C D 8
Edge (u v weight):  C E 10
Enter number of nodes:  6
Node and Heuristic (node h):  A 7
Node and Heuristic (node h):  B 6
Node and Heuristic (node h):  C 2
Node and Heuristic (node h):  D 1
Node and Heuristic (node h):  E 0
Node and Heuristic (node h):  


ValueError: not enough values to unpack (expected 2, got 0)

In [22]:
# 6) Best FS Algo - undirected|weighted

import heapq

def read_graph():
    g = {}
    for _ in range(int(input("Edges: "))):
        u, v, w = input().upper().split()
        g.setdefault(u, []).append((v, int(w)))
        g.setdefault(v, []).append((u, int(w)))
    return g

def read_heuristics():
    return {node.upper(): int(h) for node, h in 
            (input("Node Heuristic: ").split() for _ in range(int(input("Nodes: "))))}

def best_first_search(g, h, start, goal):
    visited, q = set(), [(h[start], start)]
    while q:
        _, node = heapq.heappop(q)
        if node in visited: continue
        print(node, end=' ')
        if node == goal:
            print("\nGoal reached!")
            return
        visited.add(node)
        for neighbor, _ in g.get(node, []):
            if neighbor not in visited:
                heapq.heappush(q, (h[neighbor], neighbor))
    print("\nGoal not reachable.")

g = read_graph()
h = read_heuristics()
start, goal = input("Start: ").upper(), input("Goal: ").upper()
print("\nBest First Search Traversal:")
best_first_search(g, h, start, goal)


Edges:  5
 A B 4
 A C 2
 B D 5
 C D 8
 C E 10
Nodes:  5
Node Heuristic:  A 7
Node Heuristic:  B 6
Node Heuristic:  C 2
Node Heuristic:  D 1
Node Heuristic:  E 0
Start:  A
Goal:  E



Best First Search Traversal:
A C E 
Goal reached!


In [24]:
# 7) Best FS Algo - undirected| Unweighted

import heapq

def read_graph():
    g = {}
    for _ in range(int(input("Edges: "))):
        u, v = input("Edge (u v): ").upper().split()
        g.setdefault(u, []).append(v)
        g.setdefault(v, []).append(u)
    return g

def read_heuristics():
    return {node.upper(): int(h) for node, h in 
            (input("Node Heuristic: ").split() for _ in range(int(input("Nodes: "))))}

def best_first_search(g, h, start, goal):
    visited, q = set(), [(h[start], start)]
    while q:
        _, node = heapq.heappop(q)
        if node in visited: continue
        print(node, end=' ')
        if node == goal:
            print("\nGoal reached!")
            return
        visited.add(node)
        for neighbor in g.get(node, []):
            if neighbor not in visited:
                heapq.heappush(q, (h[neighbor], neighbor))
    print("\nGoal not reachable.")

g = read_graph()
h = read_heuristics()
start, goal = input("Start: ").strip().upper(), input("Goal: ").strip().upper()
print("\nBest First Search Traversal:")
best_first_search(g, h, start, goal)


Edges:  5
Edge (u v):  A B
Edge (u v):  A C
Edge (u v):  B D
Edge (u v):  C D
Edge (u v):  C E
Nodes:  5
Node Heuristic:  A 7
Node Heuristic:  B 6
Node Heuristic:  C 2
Node Heuristic:  D 1
Node Heuristic:  E 0
Start:  A 
Goal:  E



Best First Search Traversal:
A C E 
Goal reached!


In [4]:
# 8)A* Algo - Directed|Weighted from CSV

import csv, heapq

def read_graph_and_heuristics(path):
    g, h = {}, {}
    with open(path) as f:
        next(f)
        for row in csv.reader(f):
            row = [x.strip() for x in row if x.strip() != '']  # Clean empty cells
            if not row:
                continue
            if len(row) == 3:
                u, v, w = row[0].upper(), row[1].upper(), int(row[2])
                g.setdefault(u, []).append((v, w))
            elif len(row) == 2:
                node, heur = row[0].upper(), int(row[1])
                h[node] = heur
    return g, h

def a_star(g, h, start, goal):
    queue, visited = [(h.get(start, 0), 0, start)], set()
    while queue:
        _, g_val, node = heapq.heappop(queue)
        if node in visited: continue
        print(node, end=' ')
        if node == goal: return print("\nGoal reached!")
        visited.add(node)
        for nei, cost in g.get(node, []):
            if nei not in visited:
                heapq.heappush(queue, (g_val + cost + h.get(nei, 0), g_val + cost, nei))
    print("\nGoal not reachable.")

# Main
path = r"C:\Users\Vraj Shah\Downloads\sample_graph_exp 8.csv"  # Your CSV path
graph, heuristics = read_graph_and_heuristics(path)

start = input("Enter start node: ").strip().upper()
goal = input("Enter goal node: ").strip().upper()

print("\nA* Traversal:")
a_star(graph, heuristics, start, goal)


Enter start node:  B 
Enter goal node:  E



A* Traversal:
B D E 
Goal reached!


In [6]:
# 9) A* algo - Directed|Weighted from User

import heapq

def read_graph(): 
    g = {}; n = int(input("Edges? "))
    for _ in range(n):
        u, v, w = input("From, To, Weight: ").upper().split()
        g.setdefault(u, []).append((v, int(w)))
    return g

def read_heuristics():
    return {input("Node: ").upper(): int(input("Heuristic: ")) for _ in range(int(input("Nodes? ")))}

def a_star(g, h, start, goal):
    q, v = [(h.get(start, 0), 0, start)], set()
    while q:
        _, g_val, node = heapq.heappop(q)
        if node in v: continue
        print(node, end=' ')
        if node == goal: return print("\nGoal reached!")
        v.add(node)
        for nei, cost in g.get(node, []):
            if nei not in v:
                heapq.heappush(q, (g_val + cost + h.get(nei, 0), g_val + cost, nei))
    print("\nGoal not reachable.")

# Main
g, h = read_graph(), read_heuristics()
start, goal = input("Start: ").upper(), input("Goal: ").upper()

print("\nA* Traversal:")
a_star(g, h, start, goal)


Edges?  5
From, To, Weight:  A B 1
From, To, Weight:  A C 3
From, To, Weight:  B D 1
From, To, Weight:  C D 1
From, To, Weight:  D E 5
Nodes?  5
Node:  A 7
Heuristic:  7
Node:  B
Heuristic:  6
Node:  C
Heuristic:  2
Node:  D
Heuristic:  1
Node:  E
Heuristic:  0
Start:  A
Goal:  E



A* Traversal:
A C D B E 
Goal reached!


In [7]:
# 10)A* Algo - Undirected|Weighted from CSV

import csv, heapq

def read_graph_heuristics(file):
    g, h = {}, {}
    with open(file) as f:
        for r in csv.DictReader(f):
            u = r['From'].strip().upper()
            if r['Heuristic']: h[u] = int(r['Heuristic'])
            if r['To']:
                v, w = r['To'].strip().upper(), int(r['Weight'])
                g.setdefault(u, []).append((v, w))
                g.setdefault(v, []).append((u, w))  # Undirected
    return g, h

def astar(g, h, start, goal):
    q, seen = [(h.get(start, 0), 0, start)], set()
    while q:
        _, g_val, u = heapq.heappop(q)
        if u in seen: continue
        print(u, end=' ')
        if u == goal: return print("\nGoal reached!")
        seen.add(u)
        for v, cost in g.get(u, []):
            if v not in seen:
                heapq.heappush(q, (g_val + cost + h.get(v, 0), g_val + cost, v))
    print("\nGoal not reachable.")

# === Main ===
file = r"C:\Users\Vraj Shah\Downloads\sample_astar_graph_exp 10.csv" # <- Put your file path here!
g, h = read_graph_heuristics(file)
start = input("Enter start node: ").strip().upper()
goal = input("Enter goal node: ").strip().upper()

print("\nA* Traversal:")
astar(g, h, start, goal)


Enter start node:  A
Enter goal node:  E



A* Traversal:
A C D B E 
Goal reached!


In [8]:
# 11) A* Algo -  Undirected|Weighted from User

import heapq

g, h = {}, {}
for _ in range(int(input("Edges: "))):
    u, v, w = input("From: ").upper(), input("To: ").upper(), int(input("Weight: "))
    g.setdefault(u, []).append((v, w))
    g.setdefault(v, []).append((u, w))

for _ in range(int(input("Heuristic nodes: "))):
    n = input("Node: ").upper()
    h[n] = int(input(f"Heuristic {n}: "))

def astar(g, h, start, goal):
    q, seen = [(h.get(start,0), 0, start)], set()
    while q:
        _, gval, u = heapq.heappop(q)
        if u in seen: continue
        print(u, end=' ')
        if u == goal: return print("\nGoal reached!")
        seen.add(u)
        for v, cost in g.get(u, []):
            if v not in seen:
                heapq.heappush(q, (gval+cost+h.get(v,0), gval+cost, v))
    print("\nGoal not reachable.")

start = input("Start: ").strip().upper()
goal = input("Goal: ").strip().upper()
print("\nA* Traversal:")
astar(g, h, start, goal)


Edges:  5
From:  A
To:  B
Weight:  1
From:  A
To:  C
Weight:  3
From:  B
To:  D
Weight:  1
From:  C
To:  D
Weight:  1
From:  D
To:  E
Weight:  5
Heuristic nodes:  5
Node:  A
Heuristic A:  7
Node:  B
Heuristic B:  6
Node:  C
Heuristic C:  2
Node:  D
Heuristic D:  1
Node:  E
Heuristic E:  0
Start:  A
Goal:  E



A* Traversal:
A C D B E 
Goal reached!


In [9]:
# 12) Implement Fuzzy set operations -Demonstrate these operations with 3 fuzzy sets. 

# Define 3 fuzzy sets
A = {'x': 0.2, 'y': 0.5, 'z': 0.8}
B = {'x': 0.6, 'y': 0.4, 'z': 0.3}
C = {'x': 0.9, 'y': 0.7, 'z': 0.1}

# Union of two fuzzy sets
def fuzzy_union(set1, set2):
    return {k: max(set1.get(k,0), set2.get(k,0)) for k in set(set1) | set(set2)}

# Intersection of two fuzzy sets
def fuzzy_intersection(set1, set2):
    return {k: min(set1.get(k,0), set2.get(k,0)) for k in set(set1) | set(set2)}

# Complement of a fuzzy set
def fuzzy_complement(set1):
    return {k: round(1 - v, 2) for k, v in set1.items()}

# Display function
def display(title, fz_set):
    print(f"\n{title}:")
    for k, v in fz_set.items():
        print(f"{k}: {v}")

# Perform operations
union_AB = fuzzy_union(A, B)
intersection_BC = fuzzy_intersection(B, C)
complement_C = fuzzy_complement(C)

# Display results
display("Union of A and B", union_AB)
display("Intersection of B and C", intersection_BC)
display("Complement of C", complement_C)



Union of A and B:
y: 0.5
x: 0.6
z: 0.8

Intersection of B and C:
y: 0.4
x: 0.6
z: 0.1

Complement of C:
x: 0.1
y: 0.3
z: 0.9


In [10]:
# 13) Demonstrate De Morgan’s Law ( Complement of Union) with 2 fuzzy sets. 

# Define 2 fuzzy sets
A = {'x': 0.3, 'y': 0.6, 'z': 0.8}
B = {'x': 0.7, 'y': 0.4, 'z': 0.5}

# Fuzzy Operations
def fuzzy_union(set1, set2):
    return {k: max(set1.get(k,0), set2.get(k,0)) for k in set(set1) | set(set2)}

def fuzzy_intersection(set1, set2):
    return {k: min(set1.get(k,0), set2.get(k,0)) for k in set(set1) | set(set2)}

def fuzzy_complement(set1):
    return {k: round(1 - v, 2) for k, v in set1.items()}

def display(title, fz_set):
    print(f"\n{title}:")
    for k, v in fz_set.items():
        print(f"{k}: {v}")

# Operations
union_AB = fuzzy_union(A, B)
complement_union = fuzzy_complement(union_AB)

complement_A = fuzzy_complement(A)
complement_B = fuzzy_complement(B)
intersection_complements = fuzzy_intersection(complement_A, complement_B)

# Display
display("Set A", A)
display("Set B", B)
display("Union of A and B", union_AB)
display("Complement of (A ∪ B)", complement_union)
display("Complement of A", complement_A)
display("Complement of B", complement_B)
display("Intersection of complements (¬A ∩ ¬B)", intersection_complements)

# Verify De Morgan's Law
print("\nDe Morgan's Law Verified:", complement_union == intersection_complements)




Set A:
x: 0.3
y: 0.6
z: 0.8

Set B:
x: 0.7
y: 0.4
z: 0.5

Union of A and B:
y: 0.6
x: 0.7
z: 0.8

Complement of (A ∪ B):
y: 0.4
x: 0.3
z: 0.2

Complement of A:
x: 0.7
y: 0.4
z: 0.2

Complement of B:
x: 0.3
y: 0.6
z: 0.5

Intersection of complements (¬A ∩ ¬B):
y: 0.4
x: 0.3
z: 0.2

De Morgan's Law Verified: True


In [17]:
# Fuzzy Set Operations (Short Version)

A = {'x1': 0.2, 'x2': 0.7, 'x3': 1.0}
B = {'x1': 0.5, 'x2': 0.4, 'x3': 0.9}

print("Set A:", A)
print("Set B:", B)

# Operations
union = {x: max(A.get(x, 0), B.get(x, 0)) for x in set(A) | set(B)}
intersection = {x: min(A.get(x, 0), B.get(x, 0)) for x in set(A) | set(B)}
complement_A = {x: 1 - A[x] for x in A}
complement_B = {x: 1 - B[x] for x in B}

print("\nUnion (A ∪ B):", union)
print("Intersection (A ∩ B):", intersection)
print("Complement of A (A'):", complement_A)
print("Complement of B (B'):", complement_B)

# De Morgan's Law
comp_intersection = {x: 1 - intersection[x] for x in intersection}
union_complements = {x: max(complement_A.get(x, 0), complement_B.get(x, 0)) for x in set(complement_A) | set(complement_B)}

print("\nComplement of (A ∩ B):", comp_intersection)
print("Union of (A' ∪ B'):", union_complements)

print("\n De Morgan's Law Verified!" if comp_intersection == union_complements else "\n❌ De Morgan's Law Failed!")


Set A: {'x1': 0.2, 'x2': 0.7, 'x3': 1.0}
Set B: {'x1': 0.5, 'x2': 0.4, 'x3': 0.9}

Union (A ∪ B): {'x1': 0.5, 'x3': 1.0, 'x2': 0.7}
Intersection (A ∩ B): {'x1': 0.2, 'x3': 0.9, 'x2': 0.4}
Complement of A (A'): {'x1': 0.8, 'x2': 0.30000000000000004, 'x3': 0.0}
Complement of B (B'): {'x1': 0.5, 'x2': 0.6, 'x3': 0.09999999999999998}

Complement of (A ∩ B): {'x1': 0.8, 'x3': 0.09999999999999998, 'x2': 0.6}
Union of (A' ∪ B'): {'x1': 0.8, 'x3': 0.09999999999999998, 'x2': 0.6}

 De Morgan's Law Verified!


In [18]:
# 15) Modified Tic-Tac-Toe, using min-max algorithm such that in every play either computer wins or it is a draw. 

# Modified Tic-Tac-Toe (Minimax AI)

import math

def print_board(board):
    for row in board:
        print(" | ".join(row))
        print("-" * 5)

def check_winner(board):
    for line in board + list(zip(*board)) + [[board[i][i] for i in range(3)], [board[i][2-i] for i in range(3)]]:
        if all(cell == 'X' for cell in line):
            return 'X'
        if all(cell == 'O' for cell in line):
            return 'O'
    return None if any(cell == ' ' for row in board for cell in row) else 'Draw'

def minimax(board, is_maximizing):
    winner = check_winner(board)
    if winner == 'O': return 1
    if winner == 'X': return -1
    if winner == 'Draw': return 0

    best_score = -math.inf if is_maximizing else math.inf

    for i in range(3):
        for j in range(3):
            if board[i][j] == ' ':
                board[i][j] = 'O' if is_maximizing else 'X'
                score = minimax(board, not is_maximizing)
                board[i][j] = ' '
                best_score = max(score, best_score) if is_maximizing else min(score, best_score)

    return best_score

def best_move(board):
    move = None
    best_score = -math.inf

    for i in range(3):
        for j in range(3):
            if board[i][j] == ' ':
                board[i][j] = 'O'
                score = minimax(board, False)
                board[i][j] = ' '
                if score > best_score:
                    best_score = score
                    move = (i, j)
    return move

# Main Game Loop
board = [[' ']*3 for _ in range(3)]

print("Welcome to Modified Tic-Tac-Toe!")
print_board(board)

while True:
    # Player move
    try:
        row, col = map(int, input("\nEnter your move (row and column 0-2): ").split())
        if board[row][col] != ' ':
            print("Invalid move! Cell occupied.")
            continue
        board[row][col] = 'X'
    except (ValueError, IndexError):
        print("Invalid input! Enter row and column between 0-2.")
        continue

    print_board(board)
    if (result := check_winner(board)):
        print("\nResult:", result)
        break

    # Computer move
    i, j = best_move(board)
    board[i][j] = 'O'
    print("\nComputer's move:")
    print_board(board)

    if (result := check_winner(board)):
        print("\nResult:", result)
        break


Welcome to Modified Tic-Tac-Toe!
  |   |  
-----
  |   |  
-----
  |   |  
-----



Enter your move (row and column 0-2):  0 1


  | X |  
-----
  |   |  
-----
  |   |  
-----

Computer's move:
O | X |  
-----
  |   |  
-----
  |   |  
-----



Enter your move (row and column 0-2):  1 1


O | X |  
-----
  | X |  
-----
  |   |  
-----

Computer's move:
O | X |  
-----
  | X |  
-----
  | O |  
-----



Enter your move (row and column 0-2):  1 0


O | X |  
-----
X | X |  
-----
  | O |  
-----

Computer's move:
O | X |  
-----
X | X | O
-----
  | O |  
-----



Enter your move (row and column 0-2):  2 1


Invalid move! Cell occupied.



Enter your move (row and column 0-2):  2 0


O | X |  
-----
X | X | O
-----
X | O |  
-----

Computer's move:
O | X | O
-----
X | X | O
-----
X | O |  
-----



Enter your move (row and column 0-2):  2 2


O | X | O
-----
X | X | O
-----
X | O | X
-----

Result: Draw


In [19]:
# 16) Modified Tic-Tac-Toe (Bad Minimax AI - computer loses or draws)

import random

def print_board(board):
    for row in board:
        print(" | ".join(row))
        print("-" * 5)

def check_winner(board):
    lines = board + list(zip(*board)) + [[board[i][i] for i in range(3)], [board[i][2-i] for i in range(3)]]
    for line in lines:
        if all(cell == 'X' for cell in line):
            return 'X'
        if all(cell == 'O' for cell in line):
            return 'O'
    return None if any(cell == ' ' for row in board for cell in row) else 'Draw'

# BAD Minimax: Computer makes random valid moves
def bad_move(board):
    empty = [(i, j) for i in range(3) for j in range(3) if board[i][j] == ' ']
    return random.choice(empty) if empty else None

# Main Game
board = [[' ']*3 for _ in range(3)]

print("Welcome to Modified Tic-Tac-Toe (Computer loses or draws)!")
print_board(board)

while True:
    # Player move
    try:
        row, col = map(int, input("\nEnter your move (row and column 0-2): ").split())
        if board[row][col] != ' ':
            print("Invalid move! Cell occupied.")
            continue
        board[row][col] = 'X'
    except (ValueError, IndexError):
        print("Invalid input! Enter row and column between 0-2.")
        continue

    print_board(board)
    if (result := check_winner(board)):
        print("\nResult:", result)
        break

    # Computer bad move
    move = bad_move(board)
    if move:
        i, j = move
        board[i][j] = 'O'
        print("\nComputer's move:")
        print_board(board)

    if (result := check_winner(board)):
        print("\nResult:", result)
        break


Welcome to Modified Tic-Tac-Toe (Computer loses or draws)!
  |   |  
-----
  |   |  
-----
  |   |  
-----



Enter your move (row and column 0-2):  0 0


X |   |  
-----
  |   |  
-----
  |   |  
-----

Computer's move:
X |   |  
-----
  |   |  
-----
  |   | O
-----



Enter your move (row and column 0-2):  1 0


X |   |  
-----
X |   |  
-----
  |   | O
-----

Computer's move:
X |   |  
-----
X |   |  
-----
  | O | O
-----



Enter your move (row and column 0-2):  2 0


X |   |  
-----
X |   |  
-----
X | O | O
-----

Result: X


In [22]:
!pip install numpy


   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.3/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 1.5 MB/s eta 0:00:09
   ---- ----------------------------------- 1.3/12.9 MB 2.3 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.9 MB 2.5 MB/s eta 0:00:05
   -------- ------------------------------- 2.6/12.9 MB 2.7 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.9 MB 3.0 MB/s eta 0:00:04
   -------------- ------------------------- 4.7/12.9 MB 3.4 MB/s eta 0:00:03
   ------------------ --------------------- 6.0/12.9 MB 3.9 MB/s eta 0:00:02
   ---------------------- ----------------- 7.3/12.9 MB 4.2 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.9 MB 4.0 MB/s eta 0:00:02
   ------------------------- -------------- 8.1/12.9 MB 4.0 MB/s eta 0:00:02
   --------------------------- ------------ 8.9/12.9 MB 3.7 MB/s eta 0:00:02
   ----------

In [23]:
import numpy as np

# Activation function: Sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of Sigmoid (for backpropagation)
def sigmoid_derivative(x):
    return x * (1 - x)

# Function to create a simple MLP
def simple_mlp(N, max_steps=10000, learning_rate=0.1):
    # Generate random binary inputs (X) and expected outputs (y)
    X = np.random.randint(0, 2, (N, N))  # N samples, N features
    y = np.random.randint(0, 2, (N, 1))  # N samples, 1 output

    # Randomly initialize weights and biases
    np.random.seed()
    w1 = np.random.uniform(-1, 1, (N, N))  # Input to hidden1
    b1 = np.random.uniform(-1, 1, (1, N))
    
    w2 = np.random.uniform(-1, 1, (N, N))  # hidden1 to hidden2
    b2 = np.random.uniform(-1, 1, (1, N))
    
    w3 = np.random.uniform(-1, 1, (N, 1))  # hidden2 to output
    b3 = np.random.uniform(-1, 1, (1, 1))

    steps = 0
    for step in range(max_steps):
        steps += 1
        
        # Forward Pass
        z1 = np.dot(X, w1) + b1
        a1 = sigmoid(z1)
        
        z2 = np.dot(a1, w2) + b2
        a2 = sigmoid(z2)
        
        z3 = np.dot(a2, w3) + b3
        output = sigmoid(z3)
        
        # Compute Error
        error = y - output
        if np.mean(np.abs(error)) < 0.01:  # Stop if error is small enough
            break

        # Backward Pass
        d_output = error * sigmoid_derivative(output)
        d_hidden2 = d_output.dot(w3.T) * sigmoid_derivative(a2)
        d_hidden1 = d_hidden2.dot(w2.T) * sigmoid_derivative(a1)
        
        # Update Weights and Biases
        w3 += a2.T.dot(d_output) * learning_rate
        b3 += np.sum(d_output, axis=0, keepdims=True) * learning_rate
        
        w2 += a1.T.dot(d_hidden2) * learning_rate
        b2 += np.sum(d_hidden2, axis=0, keepdims=True) * learning_rate
        
        w1 += X.T.dot(d_hidden1) * learning_rate
        b1 += np.sum(d_hidden1, axis=0, keepdims=True) * learning_rate

    # Display final results
    print("Final Weights and Biases after training:\n")
    print(f"w1 (Input -> Hidden Layer 1):\n{w1}\n")
    print(f"b1 (Hidden Layer 1 bias):\n{b1}\n")
    
    print(f"w2 (Hidden Layer 1 -> Hidden Layer 2):\n{w2}\n")
    print(f"b2 (Hidden Layer 2 bias):\n{b2}\n")
    
    print(f"w3 (Hidden Layer 2 -> Output):\n{w3}\n")
    print(f"b3 (Output bias):\n{b3}\n")
    
    print(f"Total number of steps taken: {steps}")

# Example: Let's run with N=4 inputs
simple_mlp(N=4)


Final Weights and Biases after training:

w1 (Input -> Hidden Layer 1):
[[-2.57296726 -1.16195394 -1.24619125  1.56044297]
 [-1.45014009 -1.01497243  0.36655751  1.0520165 ]
 [ 1.67872779  1.66337222  0.7076231  -0.46982726]
 [-0.58687204 -1.13209812 -0.92408676  0.04146198]]

b1 (Hidden Layer 1 bias):
[[ 1.51943786  0.27670271 -0.82791378 -0.57839982]]

w2 (Hidden Layer 1 -> Hidden Layer 2):
[[ 2.14677822 -3.31033303  1.82798977 -1.56332285]
 [ 1.56195019 -1.55493669  0.88293082 -1.08152898]
 [ 1.11354177 -0.4782022   0.29751993 -0.67947616]
 [-1.29374078  2.05730494 -0.09479226  1.3694023 ]]

b2 (Hidden Layer 2 bias):
[[-0.77978391  0.65028917 -0.67188915  0.02363514]]

w3 (Hidden Layer 2 -> Output):
[[-3.33091157]
 [ 4.72217687]
 [-2.11899715]
 [ 2.35861003]]

b3 (Output bias):
[[-0.28992238]]

Total number of steps taken: 10000


In [39]:
# 18) Implement a simple Multi-Layer Perceptron with 4 binary inputs, one
# hidden layer and two binary outputs. Display the final weight matrices, bias
# values and the number of steps. Note that random values are assigned to
# weight matrices and bias in each step. 

import numpy as np

# Step activation function
def step_function(x):
    return np.where(x >= 0, 1, 0)

# Define MLP parameters
input_size = 4
hidden_size = 5   # You can choose any number for hidden neurons
output_size = 2

# Random weight initialization
W1 = np.random.randn(input_size, hidden_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(hidden_size, output_size)
b2 = np.random.randn(output_size)

# Dummy input data (4 binary inputs)
X = np.random.randint(0, 2, (1, input_size))

steps = 0
output = None

while True:
    steps += 1

    # Forward pass
    hidden_input = np.dot(X, W1) + b1
    hidden_output = step_function(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    final_output = step_function(final_input)

    # If final output is binary (0 or 1) for both outputs, break
    if np.all((final_output == 0) | (final_output == 1)):
        output = final_output
        break
    else:
        # Randomize weights and biases again
        W1 = np.random.randn(input_size, hidden_size)
        b1 = np.random.randn(hidden_size)
        W2 = np.random.randn(hidden_size, output_size)
        b2 = np.random.randn(output_size)

# Display results
print("Input X:\n", X)
print("\nFinal hidden layer weights W1:\n", W1)
print("\nFinal hidden layer bias b1:\n", b1)
print("\nFinal output layer weights W2:\n", W2)
print("\nFinal output layer bias b2:\n", b2)
print("\nFinal output:\n", output)
print("\nTotal steps taken:", steps)


Input X:
 [[1 0 1 0]]

Final hidden layer weights W1:
 [[-0.0410316   0.29180353  1.14193045 -1.48759998  0.1891206 ]
 [ 0.43944092  1.35224509  0.34405502  0.69464388  1.98709238]
 [-1.53436701  0.14317434  0.14585734  1.22938939 -1.50402059]
 [-0.3260788   0.8836129  -0.40147606  0.22181234 -2.2351063 ]]

Final hidden layer bias b1:
 [ 1.65183974  1.26872176 -0.19194276 -0.56624191  1.41490578]

Final output layer weights W2:
 [[ 0.2618235   1.24991765]
 [ 0.63790328  0.30834233]
 [ 0.49553841 -0.52469251]
 [-0.39931896 -0.20329315]
 [ 0.78615686  0.96542797]]

Final output layer bias b2:
 [ 0.38007777 -0.93102578]

Final output:
 [[1 1]]

Total steps taken: 1


In [41]:
# 19)Implement a simple Multi-Layer Perceptron with N binary inputs, two
# hidden layers and one output. Use backpropagation and Sigmoid function
# as activation function. 

import numpy as np

# Sigmoid activation and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Define MLP structure
N = 4  # Number of inputs (you can change N easily)
hidden1_size = 5
hidden2_size = 3
output_size = 1

# Random weight initialization
W1 = np.random.randn(N, hidden1_size)
b1 = np.random.randn(hidden1_size)

W2 = np.random.randn(hidden1_size, hidden2_size)
b2 = np.random.randn(hidden2_size)

W3 = np.random.randn(hidden2_size, output_size)
b3 = np.random.randn(output_size)

# Dummy training data (binary inputs and binary output)
X = np.random.randint(0, 2, (10, N))  # 10 samples
y = np.random.randint(0, 2, (10, 1))

# Training parameters
epochs = 5000
learning_rate = 0.1

# Training using Backpropagation
for epoch in range(epochs):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    z3 = np.dot(a2, W3) + b3
    output = sigmoid(z3)

    # Compute error
    error = y - output

    # Backward pass
    d_output = error * sigmoid_derivative(output)
    
    d_hidden2 = np.dot(d_output, W3.T) * sigmoid_derivative(a2)
    
    d_hidden1 = np.dot(d_hidden2, W2.T) * sigmoid_derivative(a1)

    # Update weights and biases
    W3 += learning_rate * np.dot(a2.T, d_output)
    b3 += learning_rate * np.sum(d_output, axis=0)

    W2 += learning_rate * np.dot(a1.T, d_hidden2)
    b2 += learning_rate * np.sum(d_hidden2, axis=0)

    W1 += learning_rate * np.dot(X.T, d_hidden1)
    b1 += learning_rate * np.sum(d_hidden1, axis=0)

# Final Results
print("\nTraining complete!")
print("\nFinal Input X:\n", X)
print("\nExpected Output y:\n", y)
print("\nFinal Output after training:\n", np.round(output))
print("\nFinal Weights and Biases:")
print("\nW1:\n", W1)
print("\nb1:\n", b1)
print("\nW2:\n", W2)
print("\nb2:\n", b2)
print("\nW3:\n", W3)
print("\nb3:\n", b3)



Training complete!

Final Input X:
 [[1 1 1 0]
 [0 0 1 0]
 [0 1 1 0]
 [1 0 0 1]
 [0 1 1 0]
 [0 1 0 1]
 [0 0 0 0]
 [1 1 0 1]
 [0 1 0 1]
 [0 1 0 0]]

Expected Output y:
 [[1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]]

Final Output after training:
 [[1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]]

Final Weights and Biases:

W1:
 [[-2.55445475 -2.15083361  0.99534847  0.38239427 -1.9960841 ]
 [-3.66727325  1.87589873  1.09897075  1.28305597 -1.11904212]
 [ 3.17326831  1.53481678 -1.90463115 -0.16661581  0.01695143]
 [-1.86780334  4.00943531  0.55108136  1.97956916  0.34763185]]

b1:
 [-0.7117431  -2.04186313 -1.75185446  2.26582838  1.70981582]

W2:
 [[-2.73195418  4.10781599  3.64133416]
 [-2.63910968  2.7175162   2.62260112]
 [-0.52558934  1.99141888  1.08521672]
 [ 1.87181805 -1.73757238 -0.90527455]
 [ 1.44405515 -1.91081543 -2.45711319]]

b2:
 [-0.15360103 -0.66160177 -0.72712138]

W3:
 [[ 4.39112425]
 [-5.69815166]
 [-4.53744416]]

b3:
 [2.45245497]


In [48]:
import numpy as np

# Sigmoid and its derivative
sigmoid = lambda x: 1 / (1 + np.exp(-x))
sigmoid_deriv = lambda x: x * (1 - x)

# Structure
N, h1, h2, out = 4, 5, 3, 1
X = np.random.randint(0, 2, (10, N))
y = np.random.randint(0, 2, (10, 1))

# Random weights and biases
W1, b1 = np.random.randn(N, h1), np.random.randn(h1)
W2, b2 = np.random.randn(h1, h2), np.random.randn(h2)
W3, b3 = np.random.randn(h2, out), np.random.randn(out)

# Training
for _ in range(5000):
    a1 = sigmoid(X @ W1 + b1)
    a2 = sigmoid(a1 @ W2 + b2)
    out_pred = sigmoid(a2 @ W3 + b3)

    error = y - out_pred
    d_out = error * sigmoid_deriv(out_pred)
    d_h2 = (d_out @ W3.T) * sigmoid_deriv(a2)
    d_h1 = (d_h2 @ W2.T) * sigmoid_deriv(a1)

    W3 += 0.1 * a2.T @ d_out; b3 += 0.1 * d_out.sum(0)
    W2 += 0.1 * a1.T @ d_h2; b2 += 0.1 * d_h2.sum(0)
    W1 += 0.1 * X.T @ d_h1; b1 += 0.1 * d_h1.sum(0)

# Output
print("\nX:\n", X)
print("\ny:\n", y)
print("\nFinal Output:\n", np.round(out_pred))
print("\nW1:\n", W1, "\nb1:\n", b1)
print("\nW2:\n", W2, "\nb2:\n", b2)
print("\nW3:\n", W3, "\nb3:\n", b3)



X:
 [[1 1 1 0]
 [0 0 0 0]
 [0 1 1 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 1]
 [1 1 1 1]
 [0 1 1 1]
 [0 0 0 1]]

y:
 [[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]]

Final Output:
 [[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]]

W1:
 [[-0.78969374  0.13620941  2.12910416  1.48881481  2.80240248]
 [-0.68786214  2.84885921  1.85073692  2.45761665  1.03185645]
 [-1.01274347  1.35133146  0.8800574   1.65694021  0.84524494]
 [-0.40167145 -3.14312622  0.62551629  2.36554897  0.09125746]] 
b1:
 [-1.56258723  1.63072713  0.34775157 -0.85855873 -3.38811011]

W2:
 [[ 0.7188879  -1.58386828 -0.23612709]
 [ 0.81308514 -1.25351891  3.86302288]
 [-0.18783689  1.42776731 -1.47281887]
 [-0.17088763  0.94086117 -3.7272438 ]
 [ 0.61762799 -2.20415967  3.35274977]] 
b2:
 [-0.59842465 -0.15545328  0.41385123]

W3:
 [[-0.9891631 ]
 [ 2.77257352]
 [-7.3358372 ]] 
b3:
 [2.24467102]


In [42]:
# 20)Implement a simple Multi-Layer Perceptron with N binary inputs, two
# hidden layers and one output. Use backpropagation and ReLU function as
# activation function. 


import numpy as np

# ReLU and its derivative
relu = lambda x: np.maximum(0, x)
relu_deriv = lambda x: (x > 0).astype(float)

# Setup
N, h1, h2, out = 4, 5, 3, 1
X = np.random.randint(0, 2, (10, N))
y = np.random.randint(0, 2, (10, 1))

# Random weights and biases
W1, b1 = np.random.randn(N, h1), np.random.randn(h1)
W2, b2 = np.random.randn(h1, h2), np.random.randn(h2)
W3, b3 = np.random.randn(h2, out), np.random.randn(out)

# Training
for _ in range(5000):
    a1 = relu(X @ W1 + b1)
    a2 = relu(a1 @ W2 + b2)
    out_pred = relu(a2 @ W3 + b3)

    error = y - out_pred
    d_out = error * relu_deriv(out_pred)
    d_h2 = (d_out @ W3.T) * relu_deriv(a2)
    d_h1 = (d_h2 @ W2.T) * relu_deriv(a1)

    W3 += 0.01 * a2.T @ d_out; b3 += 0.01 * d_out.sum(0)
    W2 += 0.01 * a1.T @ d_h2; b2 += 0.01 * d_h2.sum(0)
    W1 += 0.01 * X.T @ d_h1; b1 += 0.01 * d_h1.sum(0)

# Output
print("\nInput X:\n", X)
print("\nTarget y:\n", y)
print("\nPredicted Output:\n", np.round(out_pred))
print("\nWeights and Biases:")
print("\nW1:\n", W1, "\nb1:\n", b1)
print("\nW2:\n", W2, "\nb2:\n", b2)
print("\nW3:\n", W3, "\nb3:\n", b3)



Input X:
 [[1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]
 [0 0 0 1]
 [0 0 1 1]
 [1 1 1 1]
 [0 1 1 0]
 [1 1 1 1]
 [0 1 1 1]
 [1 1 0 0]]

Target y:
 [[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]]

Predicted Output:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]]

Weights and Biases:

W1:
 [[ 0.88474576  1.36808328  0.07144241  0.09324905 -1.04656037]
 [-0.05796008  0.88661389 -0.67030724 -0.17550487  1.41639372]
 [ 0.16049604  0.13922503  1.39758542 -0.20317397  0.01977739]
 [-0.40342004 -1.28988348 -0.79792231 -2.11886028  0.89666267]] 
b1:
 [-0.75776261  0.51172474 -0.44880151  1.09706334 -1.41519948]

W2:
 [[ 0.53608899 -0.06319375 -0.5233127 ]
 [ 0.63628524 -0.13744583 -0.05202903]
 [-0.51082596 -1.60780251 -0.32007661]
 [-0.1873157   0.2195473  -0.70032094]
 [-0.67172052  0.63927926  0.48708493]] 
b2:
 [ 1.46007953 -0.22123902  0.12010799]

W3:
 [[-0.92003952]
 [ 0.73196718]
 [ 1.34290339]] 
b3:
 [0.93446596]


In [50]:
import numpy as np

# Tanh and its derivative
tanh = lambda x: np.tanh(x)
tanh_deriv = lambda x: 1 - np.tanh(x)**2

# Setup
N, h1, h2, out = 4, 5, 3, 1
X = np.random.randint(0, 2, (10, N))
y = np.random.randint(0, 2, (10, 1))

# Random weights and biases
W1, b1 = np.random.randn(N, h1), np.random.randn(h1)
W2, b2 = np.random.randn(h1, h2), np.random.randn(h2)
W3, b3 = np.random.randn(h2, out), np.random.randn(out)

# Training
for _ in range(5000):
    a1 = tanh(X @ W1 + b1)
    a2 = tanh(a1 @ W2 + b2)
    out_pred = tanh(a2 @ W3 + b3)

    error = y - out_pred
    d_out = error * tanh_deriv(out_pred)
    d_h2 = (d_out @ W3.T) * tanh_deriv(a2)
    d_h1 = (d_h2 @ W2.T) * tanh_deriv(a1)

    W3 += 0.01 * a2.T @ d_out; b3 += 0.01 * d_out.sum(0)
    W2 += 0.01 * a1.T @ d_h2; b2 += 0.01 * d_h2.sum(0)
    W1 += 0.01 * X.T @ d_h1; b1 += 0.01 * d_h1.sum(0)

# Output
print("\nInput X:\n", X)
print("\nTarget y:\n", y)
print("\nPredicted Output:\n", np.round(out_pred))
print("\nWeights and Biases:")
print("\nW1:\n", W1, "\nb1:\n", b1)
print("\nW2:\n", W2, "\nb2:\n", b2)
print("\nW3:\n", W3, "\nb3:\n", b3)



Input X:
 [[0 1 1 1]
 [0 0 1 1]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 1 1]
 [1 1 1 0]
 [1 1 1 1]
 [0 0 1 0]
 [1 0 1 0]
 [0 1 0 0]]

Target y:
 [[0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]]

Predicted Output:
 [[-0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [-0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]]

Weights and Biases:

W1:
 [[ 0.68075238  1.03968008  1.41703038  0.89401232  0.49727056]
 [-2.04624181 -1.23267467  1.4842481  -0.41272216 -0.49164396]
 [-0.8665011  -1.43201912 -0.2138146  -0.52050544 -1.80060796]
 [ 0.7659396   1.00754259  1.56239886 -0.17961439 -1.45828695]] 
b1:
 [ 1.36331068 -0.31408979 -0.53297239 -1.4109589   0.00437003]

W2:
 [[ 1.97673958  1.07972611  0.63209803]
 [-0.84409575 -0.77725052 -1.92427574]
 [ 0.81459789  0.71755601  1.18583205]
 [ 0.16916452  1.33117213  0.37619344]
 [ 0.15902661  0.43143186  0.62573819]] 
b2:
 [ 0.92794325  2.00300852 -0.88140559]

W3:
 [[-0.6451436 ]
 [ 0.4680761 ]
 [-2.67652401]] 
b3:
 [1.76265396]


In [58]:
!pip install re
!pip install nltk
!pip install textblob

ERROR: Could not find a version that satisfies the requirement re (from versions: none)
ERROR: No matching distribution found for re


   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------------------------------- 624.3/624.3 kB 3.3 MB/s eta 0:00:00


In [2]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')



[nltk_data] Downloading package punkt to C:\Users\Vraj
[nltk_data]     Shah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Vraj
[nltk_data]     Shah\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
# 22)Write a program to read a text file with at least 30 sentences and 200 words
# and perform the following tasks in the given sequence.
# a. Text cleaning by removing punctuation/special characters, numbers
# and extra white spaces. Use regular expression for the same.
# b. Convert text to lowercase
# c. Tokenization
# d. Remove stop words
# e. Correct misspelled words 

import re
import nltk
from nltk.corpus import stopwords
from textblob import TextBlob

nltk.download('stopwords')

file_path = r"C:\Users\Vraj Shah\OneDrive\Desktop\The sun rises in the east. Birds ch.txt"
with open(file_path, 'r', encoding='utf-8') as f:
    text = f.read()

# Cleaning
text = re.sub(r'[^a-zA-Z\s]', '', text)
text = re.sub(r'\s+', ' ', text)
text = text.lower()

# Tokenization (simple way)
tokens = text.split()

# Remove Stopwords
stop_words = set(stopwords.words('english'))
filtered_tokens = [word for word in tokens if word not in stop_words]

# Correct Spelling
corrected_tokens = [str(TextBlob(word).correct()) for word in filtered_tokens]

# Final output
print("\nCleaned and Corrected Text:\n")
print(' '.join(corrected_tokens))


[nltk_data] Downloading package stopwords to C:\Users\Vraj
[nltk_data]     Shah\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!



Cleaned and Corrected Text:

sun rises east birds chip morning flowers bloom fresh colors children play parts books hold key wisdom music soothe soul rain nourished earth trees sway gentle breeze rivers flow endless seas mountains stand tall proud stars shine brightly night moon grows soft light people walk dogs evening artists paint beautiful landscape writers imagine fantastic worlds teachers educate future generations farmers cultivate crops care scientists explore universe doctors heal sick engineers build amazing structures athletes push limits win poets express emotions words leaders inspire change friends share laughter sorrows families celebrate festival together dreams fuel ambitions challenges teach residence opportunities knock quietly courage opens new doors hope lights darkness paths kindness spreads warmth gratitude strengthens bonds learning never ends travel broaden horizons reading enriches minds conversations create connections silence brings peace patience bears fru

In [7]:
# 23) Write a program to read a text file with at least 30 sentences and 200 words
# and perform the following tasks in the given sequence.
# a. Text cleaning by removing punctuation/special characters, numbers
# and extra white spaces. Use regular expression for the same.
# b. Convert text to lowercase
# c. Stemming and Lemmatization
# d. Create a list of 3 consecutive words after lemmatization 


import re
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('wordnet')
nltk.download('omw-1.4')

# Step 1: Read File
file_path = r"C:\Users\Vraj Shah\OneDrive\Desktop\The sun rises in the east. Birds ch.txt" # <<< Change accordingly
with open(file_path, 'r', encoding='utf-8') as f:
    text = f.read()

# Step 2: Text Cleaning
text = re.sub(r'[^a-zA-Z\s]', '', text)
text = re.sub(r'\s+', ' ', text)

# Step 3: Lowercase
text = text.lower()

# Step 4: Tokenization (Simple Split)
tokens = text.split()

# Step 5: Stemming
stemmer = PorterStemmer()
stemmed_tokens = [stemmer.stem(word) for word in tokens]

# Step 6: Lemmatization
lemmatizer = WordNetLemmatizer()
lemmatized_tokens = [lemmatizer.lemmatize(word) for word in stemmed_tokens]

# Step 7: 3-Consecutive Words (triplets)
triplets = [' '.join(lemmatized_tokens[i:i+3]) for i in range(len(lemmatized_tokens)-2)]

# Final Outputs
print("\nLemmatized Tokens:\n", lemmatized_tokens)
print("\nList of 3-Consecutive Words:\n", triplets)



Lemmatized Tokens:
 ['the', 'sun', 'rise', 'in', 'the', 'east', 'bird', 'chirp', 'in', 'the', 'morn', 'flower', 'bloom', 'with', 'fresh', 'color', 'child', 'play', 'in', 'the', 'park', 'book', 'hold', 'the', 'key', 'to', 'wisdom', 'music', 'sooth', 'the', 'soul', 'rain', 'nourish', 'the', 'earth', 'tree', 'sway', 'in', 'the', 'gentl', 'breez', 'river', 'flow', 'endlessli', 'to', 'the', 'sea', 'mountain', 'stand', 'tall', 'and', 'proud', 'star', 'shine', 'brightli', 'at', 'night', 'the', 'moon', 'glow', 'with', 'soft', 'light', 'peopl', 'walk', 'their', 'dog', 'in', 'the', 'even', 'artist', 'paint', 'beauti', 'landscap', 'writer', 'imagin', 'fantast', 'world', 'teacher', 'educ', 'futur', 'gener', 'farmer', 'cultiv', 'crop', 'with', 'care', 'scientist', 'explor', 'the', 'univers', 'doctor', 'heal', 'the', 'sick', 'engin', 'build', 'amaz', 'structur', 'athlet', 'push', 'their', 'limit', 'to', 'win', 'poet', 'express', 'emot', 'in', 'word', 'leader', 'inspir', 'chang', 'friend', 'share', 

[nltk_data] Downloading package wordnet to C:\Users\Vraj
[nltk_data]     Shah\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\Vraj
[nltk_data]     Shah\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [8]:
# 24) Write a program to read a 3 text files on any technical concept with at least
# 20 sentences and 150 words. Implement one-hot encoding. 

import re

# Function to read and clean text
def read_and_clean(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        text = f.read()
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text

# Function to create vocabulary
def build_vocab(texts):
    vocab = set()
    for text in texts:
        vocab.update(text.split())
    vocab = sorted(list(vocab))  # Sort for consistent order
    return vocab

# Function to one-hot encode a text
def one_hot_encode(text, vocab):
    words = text.split()
    word_to_index = {word: idx for idx, word in enumerate(vocab)}
    one_hot_vectors = []
    for word in words:
        vector = [0] * len(vocab)
        if word in word_to_index:
            vector[word_to_index[word]] = 1
        one_hot_vectors.append(vector)
    return one_hot_vectors

# Step 1: Read and Clean the 3 files
file1 = r"C:\Users\Vraj Shah\OneDrive\Desktop\Exp 24 - Artificial Intelligence, often abbr.txt" # Change this
file2 = r"C:\Users\Vraj Shah\OneDrive\Desktop\Exp 24 - Blockchain is a distributed ledger.txt" # Change this
file3 = r"C:\Users\Vraj Shah\OneDrive\Desktop\Exp 24 - Cloud computing is the delivery of.txt"  # Change this

text1 = read_and_clean(file1)
text2 = read_and_clean(file2)
text3 = read_and_clean(file3)

texts = [text1, text2, text3]

# Step 2: Build vocabulary from all files
vocab = build_vocab(texts)
print("Vocabulary Size:", len(vocab))
print("Vocabulary List:\n", vocab)

# Step 3: One-Hot Encode each text
encoded_texts = [one_hot_encode(text, vocab) for text in texts]

# Step 4: Display results
for i, encoded in enumerate(encoded_texts, start=1):
    print(f"\nOne-Hot Encoding for File {i}:")
    for vector in encoded[:10]:  # Show only first 10 vectors for readability
        print(vector)


Vocabulary Size: 394
Vocabulary List:
 ['a', 'abbreviated', 'about', 'access', 'across', 'advancements', 'agents', 'agreement', 'ai', 'aidriven', 'aim', 'alexa', 'algorithms', 'allows', 'also', 'although', 'amazon', 'amount', 'an', 'analytics', 'analyze', 'and', 'another', 'applications', 'are', 'artificial', 'as', 'assets', 'assist', 'assistants', 'assure', 'attacks', 'authority', 'automatically', 'autonomous', 'autonomously', 'avoid', 'azure', 'backbone', 'bank', 'based', 'basis', 'behind', 'being', 'bias', 'big', 'bitcoin', 'block', 'blockchain', 'blockchains', 'blocks', 'branch', 'brings', 'build', 'businesses', 'by', 'can', 'capabilities', 'carefully', 'centers', 'central', 'certifications', 'chain', 'chains', 'challenge', 'change', 'changes', 'climate', 'closer', 'cloud', 'cloudnative', 'clouds', 'code', 'coded', 'collaboration', 'combine', 'companies', 'complex', 'compliance', 'composed', 'computation', 'computer', 'computing', 'concepts', 'concern', 'concerns', 'consensus', 'co

In [13]:
!pip install scikit-learn

from sklearn.feature_extraction.text import CountVectorizer
import os

# Step 1: Read the contents of the 3 movie review files
file_names = [
    r"C:\Users\Vraj Shah\OneDrive\Desktop\Exp 25 - The Dark Knight iReview.txt",
    r"C:\Users\Vraj Shah\OneDrive\Desktop\exp 25 - Interstellar review.txt",
    r"C:\Users\Vraj Shah\OneDrive\Desktop\Exp 25 - Inception Review.txt"
]

documents = []

for file_name in file_names:
    with open(file_name, 'r', encoding='utf-8') as file:
        documents.append(file.read())

# Step 2: Initialize CountVectorizer (Bag of Words)
vectorizer = CountVectorizer()

# Step 3: Fit and Transform the documents
X = vectorizer.fit_transform(documents)

# Step 4: Display the vocabulary
print("\nVocabulary (Words extracted):")
print(vectorizer.get_feature_names_out())

# Step 5: Display the Bag of Words Matrix
print("\nBag of Words Matrix (Word Counts):")
print(X.toarray())



Vocabulary (Words extracted):
['21st' 'achievement' 'achievements' 'act' 'action' 'adds' 'again'
 'against' 'also' 'ambitious' 'an' 'and' 'anne' 'are' 'arguably' 'as'
 'astonishing' 'attention' 'audience' 'audiences' 'avoiding' 'awe'
 'balances' 'bale' 'batman' 'be' 'beautifully' 'between' 'black' 'blends'
 'blurs' 'bond' 'book' 'both' 'breathtaking' 'brilliance' 'brilliantly'
 'brings' 'builds' 'but' 'by' 'captures' 'careful' 'case' 'cast' 'century'
 'cgi' 'challenges' 'chaos' 'character' 'characters' 'chastain' 'chilling'
 'choice' 'christian' 'christopher' 'cinema' 'cinematography' 'city'
 'classic' 'cobb' 'comic' 'compelling' 'complements' 'complex' 'concept'
 'conflicted' 'confront' 'cooper' 'core' 'could' 'crafted' 'credibility'
 'crime' 'critics' 'dark' 'daughter' 'debating' 'deliver' 'delivers'
 'demands' 'dent' 'depiction' 'depth' 'detail' 'dicaprio' 'dilation'
 'dimension' 'directed' 'direction' 'divisive' 'drama' 'dream' 'dreaming'
 'dreams' 'duality' 'dying' 'each' 'earth'

In [16]:
import math
import os

# Read files
files = [r"C:\Users\Vraj Shah\OneDrive\Desktop\Exp 26 - The Eiffel Tower.txt", r"C:\Users\Vraj Shah\OneDrive\Desktop\Exp 26 - The Statue of Liberty.txt",r"C:\Users\Vraj Shah\OneDrive\Desktop\Exp 26 - The Taj Mahal.txt"]
documents = []
for file in files:
    with open(file, 'r', encoding='utf-8') as f:
        documents.append(f.read().lower())

# Tokenize
def tokenize(text):
    return text.replace('.', '').replace(',', '').split()

tokenized_docs = [tokenize(doc) for doc in documents]

# Build Vocabulary
vocab = sorted(set(word for doc in tokenized_docs for word in doc))

# Term Frequency (TF)
def compute_tf(doc):
    tf = {}
    for word in vocab:
        tf[word] = doc.count(word) / len(doc)
    return tf

tfs = [compute_tf(doc) for doc in tokenized_docs]

# Inverse Document Frequency (IDF)
def compute_idf():
    idf = {}
    N = len(tokenized_docs)
    for word in vocab:
        df = sum(word in doc for doc in tokenized_docs)
        idf[word] = math.log((N + 1) / (df + 1)) + 1  # smoothing
    return idf

idf = compute_idf()

# TF-IDF
tfidfs = []
for tf in tfs:
    tfidf = {word: tf[word] * idf[word] for word in vocab}
    tfidfs.append(tfidf)

# Display results
for i, tfidf in enumerate(tfidfs):
    print(f"\nTF-IDF for {files[i]}:")
    sorted_words = sorted(tfidf.items(), key=lambda x: x[1], reverse=True)
    for word, score in sorted_words[:10]:  # Top 10 words
        print(f"{word}: {score:.4f}")



TF-IDF for C:\Users\Vraj Shah\OneDrive\Desktop\Exp 26 - The Eiffel Tower.txt:
the: 0.0663
it: 0.0612
tower: 0.0518
and: 0.0306
of: 0.0306
to: 0.0306
eiffel: 0.0263
is: 0.0255
was: 0.0204
as: 0.0173

TF-IDF for C:\Users\Vraj Shah\OneDrive\Desktop\Exp 26 - The Statue of Liberty.txt:
the: 0.1102
statue: 0.0574
of: 0.0508
her: 0.0430
liberty: 0.0430
a: 0.0339
hand: 0.0287
torch: 0.0287
in: 0.0254
is: 0.0254

TF-IDF for C:\Users\Vraj Shah\OneDrive\Desktop\Exp 26 - The Taj Mahal.txt:
the: 0.0862
mahal: 0.0511
taj: 0.0438
is: 0.0388
of: 0.0388
a: 0.0302
and: 0.0302
in: 0.0259
to: 0.0259
world: 0.0222
